public class ExceptionTester {

	public static void main(String[] args) {
		try {
			Class.forName("com.xworkz.Exception.ExceptionTester");
		}
		catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
		
		
		
		
		
		
/*String  i= "80040505L";
int ii;

try {
long i1=Long.parseLong(i);
System.out.println(i1);
 ii =10/+0;
	}
catch (NumberFormatException | ArithmeticException e){
	e.printStackTrace();
	System.out.println("String data cannot be converted to numbers");
	}*/

System.out.println("adding two numbers");
System.out.println("main method ended");

}
}
		/*	// TODO Auto-generated method stub
System.out.println("method started");
try {
	int[] a=new int[3]
	
	System.out.println("Inside try block");
	String string="Gangubhai";
	System.out.println(string.indexOf('h'));
	System.out.println("end of try block");
}catch (Exception e)
{
	System.out.println("can't  access null obkect");
}
System.out.println("main method ended");
	}

}

*/


